blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Diskussion / Fragen
    url: https://github.com/MrLongNight/LightJockey/discussions
    about: Stelle allgemeine Fragen oder diskutiere Ã¼ber LightJockey
  - name: ðŸ“š Dokumentation
    url: https://github.com/MrLongNight/LightJockey/blob/main/README.md
    about: Lies die Dokumentation fÃ¼r mehr Informationen
