name: "RELEASE.01 | Create MSI Installer | Manuell"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Gib die gewünschte Release-Version an"
        required: true
        default: "v0.0.3"
  push:
    branches:
      - main
      - master

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore LightJockey.sln

      - name: Build Lösung
        run: dotnet build LightJockey.sln --configuration Release --no-restore

      - name: Publish
        # Gebe das Output-Verzeichnis absolut/predictable an!
        run: dotnet publish src/LightJockey/LightJockey.csproj --configuration Release --output $(pwd)/publish --runtime win-x64 --self-contained:false

      - name: Install WiX v4
        run: dotnet tool install wix --version 4.0.4 --tool-path .wix

      - name: Build MSI
        run: .wix/wix.exe build installer/Product.wxs -o installer/LightJockey.msi

      - name: Upload MSI als Artefakt
        uses: actions/upload-artifact@v4
        with:
          name: LightJockey-Installer
          path: installer/LightJockey.msi
