name: "TASK-A.01_Start-Task_on-Issue-Label_AUTO.yml"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  submit-task:
    uses: ./.github/workflows/TASK-A.00_Reusable-Start-Task_on-Workflow-Call_AUTO.yml
    secrets:
      jules_api_key: ${{ secrets.JulesAPIKey }}
    with:
      automation_enabled: ${{ vars.JULES_AUTOMATION_ENABLED }}
